version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3 # PostGIS가 미리 설치된 공식 이미지 사용
    container_name: ecopulse-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sol
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ecopulse
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: